Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -238,11 +238,11 @@ jobs:
           name: Run migrations
           command: |
             # Your code here
-              cd backend
-              npm install
-              # Run and sve the migration output
-              npm run migrations > migrations_dump.txt
-              #exit 1
+            cd backend
+            npm install
+            # Run and sve the migration output
+            npm run migrations > migrations_dump.txt
+            #exit 1
       - run:
           name: Send migration results to memstash
           command: |
@@ -330,30 +330,53 @@ jobs:
       # Here's where you will add some code to rollback on failure  
       - destroy-environment 
  
-# smoke-test:
-#   docker:
-#     - image: circleci/node:13.8.0
-#     # Lightweight Docker image 
-#   steps:
-#     # Checkout code from git
-#     - run:
-#         name: Install dependencies
-#         command: |
-#           # your code here
-#     - run:
-#         name: Get backend url
-#         command: |
-#           # your code here
-#     - run:
-#         name: Backend smoke test.
-#         command: |
-#           # your code here
-#     - run:
-#         name: Frontend smoke test.
-#         command: |
-#           # your code here
-#     # Here's where you will add some code to rollback on failure  
-#
+  smoke-test:
+    docker:
+      - image: python:3.7-alpine3.11
+      # Lightweight Docker image 
+    steps:
+      - checkout
+      # Checkout code from git
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update ansible
+            pip install awscli
+            apk add curl
+            # your code here
+      - run:
+          name: Get backend url
+          command: |
+            # your code here
+      - run:
+          name: Backend smoke test.
+          command: |
+            # Fetch and prepare the BACKEND_IP env var
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "${API_URL}"
+            if curl "${API_URL}/api/status" | grep "ok"
+            then
+                return 0
+            else
+                return 1
+            fi
+            # your code here
+      - run:
+          name: Frontend smoke test.
+          command: |
+            # your code here
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
+            then
+                # Change this to 0 after the job fails
+              return 1
+            else
+              return 1
+            fi
+      # Here's where you will add some code to rollback on failure 
+      - destroy-environment  
+ 
 # cloudfront-update:
 #   docker:
 #     - image: circleci/node:13.8.0
